### ISSUE TITLE
Question about the performance

### ISSUE THREAD

**Issue by yichuan9527** [vana77/Bottom-up-Clustering-Person-Re-identification#4]
Hello, I set hyper-parameters 0.005 for size_penalty and 0.05 for merge_percent in your code. But on MARS, the highest rank-1 is 59.5% and the heighest mAP is  35.6%. I can't  reproduce the performance of your papers. Is my hyper-parameters set wrong?

**Comment by Mickeybaby** [comment]
@yichuan9527 
Hi,
When I run the sh ./run.sh:
(bottom-up-reID) mickey@a208-System-Product-Name:/Bottom-up-Clustering-Person-Re-identification$ python --versionPython 3.6.0 :: Continuum Analytics, Inc.
(bottom-up-reID) mickey@a208-System-Product-Name:/Bottom-up-Clustering-Person-Re-identification$ sh ./run.sh
Traceback (most recent call last):
File "run.py", line 2, in
from reid.bottom_up import *
File "/home/mickey/Bottom-up-Clustering-Person-Re-identification/reid/init.py", line 6, in
from . import metric_learning
File "/home/mickey/Bottom-up-Clustering-Person-Re-identification/reid/metric_learning/init.py", line 3, in
from metric_learn import (ITML_Supervised, LMNN, LSML_Supervised,
File "/home/mickey/miniconda3/envs/bottom-up-reID/lib/python3.6/site-packages/metric_learn/init.py", line 8, in
from .sdml import SDML, SDML_Supervised
File "/home/mickey/miniconda3/envs/bottom-up-reID/lib/python3.6/site-packages/metric_learn/sdml.py", line 15, in
from sklearn.utils.extmath import pinvh
ImportError: cannot import name 'pinvh'
Can you give me some advice ?
Best wishes to you!

**Comment by yichuan9527** [comment]
> @yichuan9527
> Hi,
> When I run the sh ./run.sh:
> (bottom-up-reID) mickey@a208-System-Product-Name:/Bottom-up-Clustering-Person-Re-identification$ python --versionPython 3.6.0 :: Continuum Analytics, Inc.
> (bottom-up-reID) mickey@a208-System-Product-Name:/Bottom-up-Clustering-Person-Re-identification$ sh ./run.sh
> Traceback (most recent call last):
> File "run.py", line 2, in
> from reid.bottom_up import *
> File "/home/mickey/Bottom-up-Clustering-Person-Re-identification/reid/init.py", line 6, in
> from . import metric_learning
> File "/home/mickey/Bottom-up-Clustering-Person-Re-identification/reid/metric_learning/init.py", line 3, in
> from metric_learn import (ITML_Supervised, LMNN, LSML_Supervised,
> File "/home/mickey/miniconda3/envs/bottom-up-reID/lib/python3.6/site-packages/metric_learn/init.py", line 8, in
> from .sdml import SDML, SDML_Supervised
> File "/home/mickey/miniconda3/envs/bottom-up-reID/lib/python3.6/site-packages/metric_learn/sdml.py", line 15, in
> from sklearn.utils.extmath import pinvh
> ImportError: cannot import name 'pinvh'
> Can you give me some advice ?
> Best wishes to you!

Hi, this blog (https://blog.csdn.net/zs15321583801/article/details/79672202) may help you .

**Comment by Mickeybaby** [comment]
@yichuan9527 Thank you for your help.
But it can't work for me.
I'm so confused about it.I really want to run it.

**Comment by Mickeybaby** [comment]
@yichuan9527 Thank you！I solved it.

**Comment by vana77** [comment]
Hi @yichuan9527 ,
Maybe you can change the batchsize to 64, and train 3 epochs for each iteration after the initialization (if self.is_video, set self.later_steps = 3 in reid/bottom_up.py). I got rank1=61.8, and map=42.7 when using these parameters.

**Comment by LuMpig** [comment]
step:  1
Create dataloader for Training with batch_size 16
Epoch: [0][340/1032]	Time 0.089 (0.091)	Data 0.000 (0.001)	Loss 10.161 (10.234)	Prec 0.00% (1.18%)	
Epoch: [0][680/1032]	Time 0.090 (0.090)	Data 0.000 (0.001)	Loss 9.907 (9.952)	Prec 0.00% (1.76%)	
Epoch: [0][1020/1032]	Time 0.091 (0.090)	Data 0.000 (0.000)	Loss 9.838 (9.784)	Prec 0.00% (2.09%)	
Epoch: [1][340/1032]	Time 0.090 (0.091)	Data 0.000 (0.000)	Loss 5.633 (6.353)	Prec 31.25% (15.55%)	
Epoch: [1][680/1032]	Time 0.090 (0.090)	Data 0.000 (0.000)	Loss 6.508 (6.319)	Prec 0.00% (14.17%)	
Epoch: [1][1020/1032]	Time 0.091 (0.090)	Data 0.000 (0.000)	Loss 6.279 (6.319)	Prec 12.50% (13.13%)	
Create dataloader for Testing with batch_size 64
Begin to extract features...
Mean AP: 10.2%
CMC Scores:
  top-1          22.9%
  top-5          38.1%
  top-10         44.6%
  top-20         51.2%
----------------------------------------bottom-up clustering------------------------------------------------
Create dataloader for Testing with batch_size 64
Begin to extract features...
run.sh: 行 14:  2748 已杀死               python run.py --dataset $dataset --logs_dir $logs -b $batchSize --size_penalty $size_penalty -mp $merge_percent

### At the beginning, I used this code to change the size_penalty value, so that I could run a few more groups, and then the above question would arise. I hope it can be answered. Thank you very much.

**Comment by Mickeybaby** [comment]
@vana77 
Hi，If I set batchsize>=1, the code doesn’t work, please help me.
if self.is_video:
            self.eval_bs = 64
            self.fixed_layer = True
            self.frames_per_video = 16
            self.later_steps = 3
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 19 and 8 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:711
Best wishes！

**Comment by Mickeybaby** [comment]
@vana77 
Can you describe the parameter settings on two video datasets in detail?
Best wishes！

**Comment by vana77** [comment]
Hi @Mickeybaby , use the original parameters in the code, it should work. However if you change the batchsize to 64, and train 3 epochs for each iteration after the initialization it might produce a higher performance on Mars. If you want to do so, please change the batchsize in run.sh. The self.eval_bs is the batchsize for evaluation, and it will out of memory if you set eval_bs>=1.
